### ISSUE TITLE
experiment with API calls to google calendar (more info in comments)

### ISSUE THREAD

**Issue by aruyten** [eagle-land/CalendarApp#25]
Each member of the dev team should become comfortable with using API calls to access data from google calendar.

To practice, we'll call a calendar holding the Cleveland Cavs Game Schedule.
The calendar_id is: nba_5_%43leveland+%43avaliers#sports@group.v.calendar.google.com

**Comment by jakeweidokal** [comment]
Access a public calendar and return data in Python. This should be done in the testapi function at the bottom of __init__.py
