### ISSUE TITLE
SQLite Database

### ISSUE THREAD

**Issue by jakeweidokal** [eagle-land/CalendarApp#38]
**What task needs done? (Should only be one thing)

1) Figure out database structure. For now, it can be _User_(id, username, password, credentials) _Friend_(id, friend_id)

2) Make an ER Diagram

3) Try to instantiate the db from our flask app. There's a link in the wiki that should help with this

4) Figure out how we can host the database on pythonanywhere.com. We can use Orin's account or Adam's account.

**Comment by aruyten** [comment]
done = database exists in amazon AWS
