### ISSUE TITLE
BUG with base.html

### ISSUE THREAD

**Issue by aruyten** [eagle-land/CalendarApp#43]
For Brian and myself the entire flask app will not run unless we comment out lines 27-29 in 'templates/base.html'.  produces some error involving the calendar object

Related to #18

**Comment by MolSnoo** [comment]
Issue can be solved by adding a route to '/calendar' in __init__.py. The reason it crashes now is because it tries to get the URL for the calendar route but there is none.

**Comment by Orinhiggins** [comment]
@eagle-land/everyone 
This has been reviewed and cleared by Jared, It is now moved to "Done- Current Sprint"
