### ISSUE TITLE
Display Schedules

### ISSUE THREAD

**Issue by mmaille** [eagle-land/CalendarApp#48]
| As a/an                         | I want to...  | So that...  | Notes  |
|----|----|----|----|
| developer  | display a single user's Google Calendar data  | we have scheduled dates to display  | Done #1: The scheduled dates from a google calendar are displayed on our website.  |   |
|   |   |   | Done #2: All tests for the calendar display of a single user are passed  |   |
|   |   |   | Done #3: Lead Developer and Lead Engineer sign off on test completion and completion of above tasks.  |   |

**Comment by Orinhiggins** [comment]
@bryceb96 @jakeweidokal @MolSnoo

Review and add your initials after review, when that is completed and everyone has signed off, then move to "Done- current sprint" please

**Comment by jakeweidokal** [comment]
Functionality for this task has been implemented. Still needs tests
