### ISSUE TITLE
Create Tests for Friend Functions in auth.py

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#54]
| As a/an  | I want to...  | So that...  | Notes  | Priority  |
|----------|--------------|-----------|---------|----------|
|  Developer  |  Test my friend invite functions | to ensure they work properly  | ---- |Done 1. Friends can be added to the users and the tests for the request_friend function 
|----|----|----|----|Done 2. Tests check_if_friend functions to determine relationship|
|----------|--------------|-----------|---------|----------Done 3. Test get_friends **all of these functions are located in auth.py*** |
|----------|--------------|-----------|---------|----------Done 4. Lead Test Engineer, Lead Developer, and Database Developer sign off on tests passing and ensuring that the task is complete  |

**Comment by lukerinehart** [comment]
BB and LR - ran under test_c_merge_calendars and the function for merge_calendars passed.
