### ISSUE TITLE
Friend_request Test Creation

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#56]
**What task needs done? (Should only be one thing)
Create Tests for the following function 
 request_friend function located in auth.py***potentially moved to another file by Adam during the week***

**Is this related to a user story? Which one?
Related to #54 

Done = Lead Test Engineer, Lead Develloper, and Test Engineer sign off on completed work.

**Comment by bryceb1108** [comment]
BB - using the test_database.py, the functions get_friends and get_pending_friends functions pass.
