### ISSUE TITLE
Tests for check_if_friends function

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#57]
**What task needs done? (Should only be one thing)
Test teh check_if_friends function is working properly by creating and conducting tests
Create Tests for the check_if_friends function in auth.py 

**Is this related to a user story? Which one?
User Story #53

Done = Lead Engineer, Lead Developer, and Test Engineer sign off on test completion

**Comment by bryceb1108** [comment]
BB - using test_database.py, check_if_friends function passes.
