### ISSUE TITLE
Tests for get_friends function

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#58]
**What task needs done? (Should only be one thing)
Test the get_friends function is working properly by creating and conducting tests
Create Tests for get_friends function in auth.py 

**Is this related to a user story? Which one?
User Story #53

Done = Lead Engineer, Lead Developer, and Test Engineer sign off on test completion

**Comment by bryceb1108** [comment]
BB - the fuction get_friends function passes using the test_database.py.
