### ISSUE TITLE
Create Tests for get_free_time function

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#59]
**What task needs done? (Should only be one thing)
Tests created for the get_free_time function located in calendar.py 
All tests work with the function

**Is this related to a user story? Which one?
Related to #53

Done = Test Engineer, Lead Engineer, and Lead Developer sign off on all tests and completion.

**Comment by Orinhiggins** [comment]
@bryceb96 @jakeweidokal 

Review and add your initials after review, when that is completed and everyone has signed off, then move to "Done- current sprint" please

**Comment by lukerinehart** [comment]
test_get_shared_freetimes.py runs and all tests pass with warnings 
-LR

**Comment by bryceb1108** [comment]
BB - test_get_shared_freetimes.py passed the tests with 5 warnings.
