### ISSUE TITLE
Create Tests for the HtML pages

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#60]
**What task needs done? (Should only be one thing)
Create Tests for HTML Pages and ensure the pages buttons etc operate correctly.

**Is this related to a user story? Which one?
Related to #15 #16 #17 #6 #48 #41

Done = Lead engineer, Test Engineer, and Lead Developer sign off on test and completion.

**Comment by Orinhiggins** [comment]
@bryceb96 @jakeweidokal 

Review and add your initials after review, when that is completed and everyone has signed off, then move to "Done- current sprint" please

**Comment by bryceb1108** [comment]
BB - test_homepage.py tested it, completed and passed the test.
