### ISSUE TITLE
Set up development environment

### ISSUE THREAD

**Issue by Orinhiggins** [eagle-land/CalendarApp#61]
**What task needs done? (Should only be one thing)
Set up everyone on their development environment, and ensure the current iteration of the calendar app works on their local machine. 

**Is this related to a user story? Which one?
NO 
Done = EVERYONE is set up to work in their environment on their local machine. 

Working - Orin Higgins 
Jake Weidokal
John Yun

Not Working -

**Comment by Orinhiggins** [comment]
@eagle-land/everyone 
If you have the dev environment working on your local machine add your name here: 


If you do not have the dev environment working on your local machine add your name here:

**Comment by bryceb1108** [comment]
Working - Bryce Benjamin

**Comment by MA-39** [comment]
Working- John Yun

**Comment by jwarre24** [comment]
working - Jessica Warren
